### ISSUE TITLE
Internal server error when uploading a layer

### ISSUE THREAD

**Issue by francbartoli** [GeoNode/geonode-workshop#22]
2017-02-05 14:34:33,129 DEBUG [org.geoserver.geofence] - Getting access limits for Layer v_tipo_attuativo_cspolygon
2017-02-05 14:34:33,130 DEBUG [org.geoserver.geofence] - Getting access limits for Resource v_tipo_attuativo_cspolygon
2017-02-05 14:34:33,130 DEBUG [org.geoserver.geofence] - Setting user for filter:
2017-02-05 14:34:33,130 DEBUG [org.geoserver.geofence] - ResourceInfo filter: RuleFilter[user:(empty)+ role:ANY inst:name+:default-gs ip:"10.0.2.2"+ serv:"WMS"+ req:"GETLEGENDGRAPHIC"+ ws:"geonode"+ layer:"v_tipo_attuativo_cspolygon"+]
2017-02-05 14:34:33,130 DEBUG [org.geoserver.geofence.cache] - Request for RuleFilter[user:(empty)+ role:ANY inst:name+:default-gs ip:"10.0.2.2"+ serv:"WMS"+ req:"GETLEGENDGRAPHIC"+ ws:"geonode"+ layer:"v_tipo_attuativo_cspolygon"+]
2017-02-05 14:34:33,133 DEBUG [org.geoserver.geofence.cache] - Loading RuleFilter[user:(empty)+ role:ANY inst:name+:default-gs ip:"10.0.2.2"+ serv:"WMS"+ req:"GETLEGENDGRAPHIC"+ ws:"geonode"+ layer:"v_tipo_attuativo_cspolygon"+]
2017-02-05 14:34:33,133 DEBUG [org.geoserver.geofence.internal] - Getting Roles for User []
2017-02-05 14:34:33,133 DEBUG [org.geoserver.geofence.internal] - Checking UserGroupService [default]
2017-02-05 14:34:33,134 DEBUG [org.geoserver.geofence.internal] - Checking RoleService [default]
2017-02-05 14:34:33,134 DEBUG [org.geoserver.geofence.internal] - Checking RoleService [geonode REST role service]
2017-02-05 14:34:33,180 ERROR [org.geoserver.ows] -
org.geoserver.platform.ServiceException: Can't obtain the schema for the required layer.
       	at org.geoserver.wms.legendgraphic.GetLegendGraphicKvpReader.read(GetLegendGraphicKvpReader.java:183)
       	at org.geoserver.wms.legendgraphic.GetLegendGraphicKvpReader.read(GetLegendGraphicKvpReader.java:77)
       	at org.geoserver.ows.Dispatcher.parseRequestKVP(Dispatcher.java:1498)
       	at org.geoserver.ows.Dispatcher.dispatch(Dispatcher.java:673)
       	at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:258)
       	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147)
       	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
       	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
       	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
       	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968)
       	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859)
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
       	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844)
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
       	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
       	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
       	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:75)
       	at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:71)
       	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
       	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:46)
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
       	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:50)
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
       	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
       	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
       	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
       	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
       	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
       	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
       	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
       	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
       	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
       	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
       	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
       	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
       	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:54)
       	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
       	at org.geoserver.security.oauth2.GeoServerOAuthAuthenticationFilter.doFilter(GeoServerOAuthAuthenticationFilter.java:132)
       	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
       	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
       	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
       	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
       	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
       	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
       	at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:84)
       	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
       	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
       	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
       	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:53)
       	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
       	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
       	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
       	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
       	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
       	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:152)
       	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
       	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
       	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:87)
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
       	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:42)
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
       	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:48)
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
       	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:44)
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
       	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
       	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
       	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
       	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
       	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
       	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
       	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
       	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
       	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
       	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
       	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
       	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
       	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
       	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
       	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
       	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
       	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
       	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
       	at org.geoserver.geofence.cache.CachedRuleReader.getAccessInfo(CachedRuleReader.java:235)
       	at org.geoserver.geofence.GeofenceAccessManager.getAccessLimits(GeofenceAccessManager.java:377)
       	at org.geoserver.geofence.GeofenceAccessManager.getAccessLimits(GeofenceAccessManager.java:293)
       	at org.geoserver.security.ResourceAccessManagerWrapper.getAccessLimits(ResourceAccessManagerWrapper.java:214)
       	at org.geoserver.security.CatalogFilterAccessManager.getAccessLimits(CatalogFilterAccessManager.java:56)
       	at org.geoserver.security.SecureCatalogImpl.buildWrapperPolicy(SecureCatalogImpl.java:806)
       	at org.geoserver.security.SecureCatalogImpl.buildWrapperPolicy(SecureCatalogImpl.java:770)
       	at org.geoserver.security.SecureCatalogImpl.checkAccess(SecureCatalogImpl.java:593)
       	at org.geoserver.security.SecureCatalogImpl.getLayerByName(SecureCatalogImpl.java:294)
       	at org.geoserver.catalog.impl.AbstractFilteredCatalog.getLayerByName(AbstractFilteredCatalog.java:225)
       	at org.geoserver.catalog.impl.AbstractCatalogDecorator.getLayerByName(AbstractCatalogDecorator.java:384)
       	at org.geoserver.catalog.impl.LocalWorkspaceCatalog.getLayerByName(LocalWorkspaceCatalog.java:92)
       	at org.geoserver.wms.WMS.getLayerByName(WMS.java:255)
       	at org.geoserver.wms.legendgraphic.GetLegendGraphicKvpReader.read(GetLegendGraphicKvpReader.java:153)
       	... 97 more
Caused by: java.lang.NullPointerException
       	at org.geoserver.geofence.internal.InternalUserResolver.existsUser(InternalUserResolver.java:74)
       	at org.geoserver.geofence.services.RuleReaderServiceImpl.validateUsername(RuleReaderServiceImpl.java:329)
       	at org.geoserver.geofence.services.RuleReaderServiceImpl.validateUserRoles(RuleReaderServiceImpl.java:534)
       	at org.geoserver.geofence.services.RuleReaderServiceImpl.getRules(RuleReaderServiceImpl.java:480)
       	at org.geoserver.geofence.services.RuleReaderServiceImpl.getAccessInfo(RuleReaderServiceImpl.java:124)
       	at org.geoserver.geofence.cache.CachedRuleReader$RuleLoader.load(CachedRuleReader.java:121)
       	at org.geoserver.geofence.cache.CachedRuleReader$RuleLoader.load(CachedRuleReader.java:113)
       	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
       	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
       	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
       	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
       	... 114 more

**Comment by francbartoli** [comment]
After installation of geonode from apt-get the REST role service is this:

```
<roleServiceName>geonode REST role service</roleServiceName>
  <cliendId>ELOKkajeJKBg6ExjVksfXFQrHCnOkcbsdnRI7gUw</cliendId>
  <clientSecret>GUxwSJWfen0I0M8eIMfsIpnW5db6jW3xi1soCZO9FksXGqVBD8uKHnh5f7PbMJLtBNyB4MxWJOftO5wByxnlNj7pbZnz4IBdwYicPFUgGjFvF63iIvUGye39lGPIOwjw</clientSecret>

  <!-- GeoNode accessTokenUri -->
  <accessTokenUri>http://localhost/o/token/</accessTokenUri>

  <!-- GeoNode userAuthorizationUri -->
  <userAuthorizationUri>http://localhost:8001/o/authorize/</userAuthorizationUri>

  <!-- GeoServer Public URL -->
  <redirectUri>http://localhost:8001/geoserver/</redirectUri>

  <!-- GeoNode checkTokenEndpointUrl -->
  <checkTokenEndpointUrl>http://localhost/api/o/v4/tokeninfo/</checkTokenEndpointUrl>

  <!-- GeoNode logoutUri -->
  <logoutUri>http://localhost:8001/account/logout/</logoutUri>
```

If I change the AuthorizationUri into:

```
 <userAuthorizationUri>http://localhost/o/authorize/</userAuthorizationUri>
```

the error disappears and layers and maps are visualized correctly. The side effect is that the user in no longer automatically authenticated in GeoServer.

**Comment by simod** [comment]
@francbartoli tested with the latest package and cannot replicate this. is it still happening for you?
